# Generated by Django 3.2.8 on 2021-10-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_good_hands_app', '0003_auto_20211008_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.CharField(default='', max_length=128),
        ),
    ]
